import React from 'react';
import {ScrollView,View,Text,Pressable,TextInput,Switch,StyleSheet,Modal,KeyboardAvoidingView,Platform,TextInputProps} from 'react-native';
import {useSafeAreaInsets} from 'react-native-safe-area-context';
import {Feather} from '@expo/vector-icons';
import {router} from 'expo-router';
import {useApp} from '../state/AppProvider';
export type IconName=React.ComponentProps<typeof Feather>['name'];
export function Icon({name,size=20,color}:{name:IconName;size?:number;color?:string}){const {colors}=useApp();return <Feather name={name} size={size} color={color||colors.coral}/>}
export function Txt({children,muted=false,size=16,bold=false,style}:{children:React.ReactNode;muted?:boolean;size?:number;bold?:boolean;style?:object}){const {colors}=useApp();return <Text style={[{fontSize:size,lineHeight:size*1.45,color:muted?colors.muted:colors.ink,fontWeight:bold?'700':'400'},style]}>{children}</Text>}
export function Title({children}:{children:React.ReactNode}){return <Txt size={28} bold style={{letterSpacing:-1,marginBottom:8}}>{children}</Txt>}
export function Eyebrow({children}:{children:React.ReactNode}){const {colors}=useApp();return <Text style={{fontSize:12,fontWeight:'700',letterSpacing:1.5,color:colors.coral,marginBottom:8}}>{children}</Text>}
export function Page({title,children,back=false,scroll=true}:{title:string;children:React.ReactNode;back?:boolean;scroll?:boolean}){const {colors,error}=useApp();const insets=useSafeAreaInsets();return <View style={{flex:1,backgroundColor:colors.bg,paddingTop:insets.top}}><View style={[styles.header,{borderColor:colors.line}]}>{back&&<Pressable accessibilityLabel="Back" accessibilityRole="button" onPress={()=>router.canGoBack()?router.back():router.replace('/')} style={styles.iconButton}><Icon name="arrow-left"/></Pressable>}<Txt bold size={18} style={{flex:1}}>{title}</Txt><Icon name="shield"/></View>{!!error&&<View style={{padding:12,backgroundColor:colors.blush}}><Txt size={12}>{error}</Txt></View>}{scroll?<ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={{padding:20,paddingBottom:Math.max(insets.bottom,20)+30}}>{children}</ScrollView>:children}</View>}
export function Card({children,style}:{children:React.ReactNode;style?:object}){const {colors}=useApp();return <View style={[{padding:16,borderWidth:1,borderColor:colors.line,backgroundColor:colors.panel,borderRadius:20,marginVertical:8},style]}>{children}</View>}
export function Button({title,onPress,secondary=false,disabled=false,icon,danger=false}:{title:string;onPress:()=>void;secondary?:boolean;disabled?:boolean;icon?:IconName;danger?:boolean}){const {colors}=useApp();return <Pressable accessibilityRole="button" disabled={disabled} onPress={onPress} style={({pressed})=>[{minHeight:50,borderRadius:15,marginVertical:6,paddingHorizontal:16,paddingVertical:13,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:10,borderWidth:1,borderColor:secondary?colors.line:'transparent',backgroundColor:secondary?colors.panel:danger?colors.red:colors.coral,opacity:disabled?.4:pressed?.7:1}]}>{icon&&<Icon name={icon} size={18} color={secondary?colors.coral:'#fff'}/>}<Text style={{color:secondary?colors.ink:'#fff',fontSize:15,fontWeight:'700',textAlign:'center'}}>{title}</Text></Pressable>}
export function Row({title,detail,icon,onPress}:{title:string;detail?:string;icon:IconName;onPress:()=>void}){const {colors}=useApp();return <Pressable accessibilityRole="button" onPress={onPress} style={[styles.row,{borderBottomColor:colors.line}]}><View style={[styles.rowIcon,{backgroundColor:colors.blush}]}><Icon name={icon}/></View><View style={{flex:1}}><Txt bold size={15}>{title}</Txt>{detail&&<Txt size={12} muted>{detail}</Txt>}</View><Icon name="chevron-right" size={17}/></Pressable>}
export function Toggle({title,detail,value,onChange}:{title:string;detail?:string;value:boolean;onChange:(v:boolean)=>void}){const {colors}=useApp();return <View style={[styles.row,{borderBottomColor:colors.line}]}><View style={{flex:1}}><Txt bold size={15}>{title}</Txt>{detail&&<Txt muted size={12}>{detail}</Txt>}</View><Switch accessibilityLabel={title} value={value} onValueChange={onChange} trackColor={{true:colors.coral,false:colors.line}}/></View>}
export function Field({label,...props}:TextInputProps&{label:string}){const {colors}=useApp();return <View style={{marginVertical:10}}><Txt size={14} bold style={{marginBottom:7}}>{label}</Txt><TextInput accessibilityLabel={label} placeholderTextColor={colors.muted} {...props} style={[{backgroundColor:colors.panel,color:colors.ink,borderWidth:1,borderColor:colors.line,borderRadius:13,padding:13,fontSize:16,minHeight:48},props.style]}/></View>}
export function Notice({children}:{children:React.ReactNode}){const {colors}=useApp();return <View style={{backgroundColor:colors.blush,padding:13,borderRadius:14,marginVertical:12,flexDirection:'row',gap:8}}><Icon name="info" size={17}/><View style={{flex:1}}><Txt size={13}>{children}</Txt></View></View>}
export function Chips<T extends string|number>({items,value,onChange}:{items:{id:T;label:string}[];value:T;onChange:(v:T)=>void}){const {colors}=useApp();return <View style={{flexDirection:'row',gap:7,flexWrap:'wrap',marginVertical:10}}>{items.map(item=><Pressable key={item.id} accessibilityRole="button" accessibilityState={{selected:value===item.id}} onPress={()=>onChange(item.id)} style={{paddingHorizontal:13,paddingVertical:11,minHeight:44,borderRadius:12,borderWidth:1,borderColor:value===item.id?colors.coral:colors.line,backgroundColor:value===item.id?colors.blush:colors.panel}}><Txt size={13} bold={value===item.id}>{item.label}</Txt></Pressable>)}</View>}
export function Sheet({title,visible,onClose,children}:{title:string;visible:boolean;onClose:()=>void;children:React.ReactNode}){const {colors}=useApp();const insets=useSafeAreaInsets();return <Modal visible={visible} animationType="slide" presentationStyle="pageSheet" onRequestClose={onClose}><KeyboardAvoidingView style={{flex:1,backgroundColor:colors.bg}} behavior={Platform.OS==='ios'?'padding':undefined}><View style={[styles.header,{borderColor:colors.line,paddingTop:12,minHeight:70}]}><Txt size={20} bold style={{flex:1}}>{title}</Txt><Pressable accessibilityLabel="Close" accessibilityRole="button" onPress={onClose} style={styles.iconButton}><Icon name="x"/></Pressable></View><ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={{padding:20,paddingBottom:insets.bottom+30}}>{children}</ScrollView></KeyboardAvoidingView></Modal>}
const styles=StyleSheet.create({header:{minHeight:60,paddingHorizontal:20,flexDirection:'row',alignItems:'center',gap:12,borderBottomWidth:1},iconButton:{minHeight:44,minWidth:44,alignItems:'center',justifyContent:'center'},row:{flexDirection:'row',alignItems:'center',gap:12,paddingVertical:15,borderBottomWidth:StyleSheet.hairlineWidth},rowIcon:{height:38,width:38,borderRadius:12,alignItems:'center',justifyContent:'center'}});
