import type {AppData,Coordinate,Incident,IncidentType,PersonalReport,Route,Trip,HistoryItem} from '../types/index.ts';
export function defaults():AppData{return {version:1,contacts:[{id:'maya',name:'Maya',phone:'202-555-0101',trip:true,sos:true},{id:'mom',name:'Mom',phone:'202-555-0102',trip:true,sos:true}],reports:[],history:[],active:null,settings:{dark:false,checkins:true,arrival:true,sharing:true,notices:true}};}
export function cutoffDate(now:Date,months:number){const d=new Date(now),day=d.getDate();d.setDate(1);d.setMonth(d.getMonth()-months);d.setDate(Math.min(day,new Date(d.getFullYear(),d.getMonth()+1,0).getDate()));d.setHours(0,0,0,0);return d;}
export function filterIncidents(records:Incident[],months:number,types:IncidentType[],now=new Date()){const start=cutoffDate(now,months).getTime(),end=new Date(now);end.setHours(23,59,59,999);return records.filter(r=>types.includes(r.type)&&Date.parse(r.occurredAt)>=start&&Date.parse(r.occurredAt)<=end.getTime());}
export function meters(a:Coordinate,b:Coordinate){const lat=(a.latitude+b.latitude)*Math.PI/360;return Math.hypot((a.latitude-b.latitude)*111320,(a.longitude-b.longitude)*111320*Math.cos(lat));}
export function positionAt(points:Coordinate[],progress:number):Coordinate{if(!points.length)return {latitude:0,longitude:0};const lengths=points.slice(1).map((p,i)=>meters(points[i],p));let remaining=lengths.reduce((a,b)=>a+b,0)*Math.max(0,Math.min(1,progress));for(let i=0;i<lengths.length;i++){if(lengths[i]>0&&remaining<=lengths[i]){const t=remaining/lengths[i];return {latitude:points[i].latitude+(points[i+1].latitude-points[i].latitude)*t,longitude:points[i].longitude+(points[i+1].longitude-points[i].longitude)*t}}remaining-=lengths[i]}return points[points.length-1];}
export function distanceToRoute(p:Coordinate,coordinates:Coordinate[]){if(!coordinates.length)return Infinity;const cos=Math.cos(p.latitude*Math.PI/180),xy=(q:Coordinate)=>({x:(q.longitude-p.longitude)*111320*cos,y:(q.latitude-p.latitude)*111320});let min=meters(p,coordinates[0]);for(let i=1;i<coordinates.length;i++){const a=xy(coordinates[i-1]),b=xy(coordinates[i]),dx=b.x-a.x,dy=b.y-a.y,len=dx*dx+dy*dy,t=len?Math.max(0,Math.min(1,-(a.x*dx+a.y*dy)/len)):0;min=Math.min(min,Math.hypot(a.x+t*dx,a.y+t*dy))}return min;}
export function nearbyIncidents(route:Route,incidents:Incident[]){return incidents.filter(i=>distanceToRoute(i.coordinate,route.coordinates)<=100).length;}
export function nearbyReports(route:Route,reports:PersonalReport[]){return reports.filter(r=>distanceToRoute(r.coordinate,route.coordinates)<=r.radius+100);}
export function incidentBreakdown(records:Incident[]){return records.reduce<Record<IncidentType,number>>((counts,record)=>({...counts,[record.type]:counts[record.type]+1}),{Theft:0,Burglary:0,Assault:0,Vandalism:0});}
export function concentrationCells(incidents:Incident[]){const south=28.532,west=-81.389,latStep=.0018,lngStep=.00204;const groups=new Map<string,{id:string;count:number;center:Coordinate;polygon:Coordinate[]}>();for(const i of incidents){const row=Math.floor((i.coordinate.latitude-south)/latStep),col=Math.floor((i.coordinate.longitude-west)/lngStep),id=`${row}:${col}`,lat=south+row*latStep,lng=west+col*lngStep;if(!groups.has(id))groups.set(id,{id,count:0,center:{latitude:lat+latStep/2,longitude:lng+lngStep/2},polygon:[{latitude:lat,longitude:lng},{latitude:lat+latStep,longitude:lng},{latitude:lat+latStep,longitude:lng+lngStep},{latitude:lat,longitude:lng+lngStep}]});groups.get(id)!.count++}return [...groups.values()].sort((a,b)=>b.count-a.count||a.id.localeCompare(b.id));}
export function finishTrip(data:AppData,status:HistoryItem['status'],now=new Date()):AppData{if(!data.active)return data;return {...data,active:null,history:[{...data.active,finishedAt:now.toISOString(),status},...data.history].slice(0,50)}}
export function advanceTrip(trip:Trip|null){return trip&&!trip.paused?{...trip,progress:Math.min(1,trip.progress+1/90)}:trip;}
export function restoreData(raw:string|null):AppData{if(!raw)return defaults();const d=JSON.parse(raw);if(d.version!==1||!Array.isArray(d.contacts)||!Array.isArray(d.reports)||!Array.isArray(d.history))throw Error('Unsupported saved data');if(d.active&&(!Array.isArray(d.active.route?.coordinates)||!d.active.destination||!Number.isFinite(d.active.progress)))throw Error('Invalid active trip');return {...defaults(),...d,settings:{...defaults().settings,...d.settings},active:d.active?{...d.active,paused:true}:null};}
export function validPhone(value:string){return /^[+()\d\s.-]{7,25}$/.test(value)&&value.replace(/\D/g,'').length>=7;}
